In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
balondor_path = '/Users/muhammadhamza/striker_era_ranking/data/raw/ballon_dor/ballon_dor_winners.csv'
seasons_path = '/Users/muhammadhamza/striker_era_ranking/data/raw/fbref/all_seasons_combined.csv'

balondor_raw = pd.read_csv(balondor_path)
seasons_raw = pd.read_csv(seasons_path)

In [4]:
seasons_raw.head()

,player,nationality,position,team,league,age,matches,minutes,goals,assists,season,assists_missing,ga_per_90
0,Agustín Abadía,ESP,MF,Compostela,La Liga,33.0,14,378,0,0,1995-1996,True,0.0
1,Beniamino Abate,ITA,GK,Cagliari,Serie A,33.0,15,1350,0,0,1995-1996,True,0.0
2,Giovanni Abate,ITA,MF,Sampdoria,Serie A,19.0,1,56,0,0,1995-1996,True,0.0
3,Denis Abed,FRA,FW,Lille,Division 1,26.0,14,925,0,0,1995-1996,True,0.0
4,Gary Ablett,ENG,DF,Everton,Premier League,29.0,13,1017,0,0,1995-1996,False,0.0

In [5]:
seasons_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74262 entries, 0 to 74261
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   player           74262 non-null  object
 1   nationality      74262 non-null  object
 2   position         74048 non-null  object
 3   team             74262 non-null  object
 4   league           74262 non-null  object
 5   age              74251 non-null  float64
 6   matches          74262 non-null  int64
 7   minutes          74262 non-null  int64
 8   goals            74262 non-null  int64
 9   assists          74262 non-null  int64
 10  season           74262 non-null  object
 11  assists_missing  74262 non-null  bool
 12  ga_per_90        74262 non-null  float64
dtypes: bool(1), float64(2), int64(4), object(6)
memory usage: 6.9+ MB

In [8]:
seasons_raw.loc[seasons_raw['league']== 'Division 1', 'team'].unique()

array(['Lille', 'Lyon', 'Gueugnon', 'Metz', 'Lens', 'Bordeaux', 'Bastia',
       'Montpellier', 'Paris Saint-Germain', 'Nice', 'Monaco', 'Rennes',
       'Saint-Étienne', 'Le Havre', 'Guingamp', 'Strasbourg', 'Cannes',
       'Martigues', 'Auxerre', 'Nantes', 'Marseille', 'Nancy', 'Caen',
       'Châteauroux', 'Toulouse', 'Lorient', 'Sochaux', 'Troyes', 'Sedan'],
      dtype=object)

In [9]:
seasons_raw['league'] = seasons_raw['league'].replace('Division 1', 'Ligue 1')
seasons_raw['league'].unique()

array(['La Liga', 'Serie A', 'Ligue 1', 'Premier League', 'Bundesliga'],
      dtype=object)

In [10]:
seasons_raw['season'].value_counts().sort_index()

season
1995-1996    2415
1996-1997    2517
1997-1998    2450
1998-1999    2468
1999-2000    2449
2000-2001    2520
2001-2002    2546
2002-2003    2593
2003-2004    2574
2004-2005    2600
2005-2006    2656
2006-2007    2597
2007-2008    2665
2008-2009    2688
2009-2010    2703
2010-2011    2709
2011-2012    2736
2012-2013    2756
2013-2014    2750
2014-2015    2692
2015-2016    2771
2016-2017    2730
2017-2018    2656
2018-2019    2656
2019-2020    2732
2020-2021    2822
2021-2022    2922
2022-2023    2889
Name: count, dtype: int64

In [11]:
balondor_raw.head()

,year,rank,player,nationality,team,club_country,points
0,1956,1,Stanley Matthews,England,Blackpool,England,47
1,1956,2,Alfredo Di Stéfano,Spain,Real Madrid,Spain,44
2,1956,3,Raymond Kopa,France,Real Madrid,Spain,33
3,1957,1,Alfredo Di Stéfano,Spain,Real Madrid,Spain,72
4,1957,2,Billy Wright,England,Wolverhampton Wanderers,England,19